In [1]:
import torch

In [8]:
# random numbers from a normal distribution with mean `0` and variance `1`
x = torch.randn(3, requires_grad=True) # creates a computational graph to calculate gradients in BackPropogation
print(x)

y = x+2
print(y)

z = y*y*2
print(z)

# z = z.mean()
# print(z)

tensor([ 0.5419,  0.4476, -1.1255], requires_grad=True)
tensor([2.5419, 2.4476, 0.8745], grad_fn=<AddBackward0>)
tensor([12.9228, 11.9819,  1.5297], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx (gradients of z with respect to x)  
# z.backward() # SCALAR --> RuntimeError: grad can be implicitly created only for scalar outputs
print(x.grad) # values for Vector Jacobian Product

tensor([1.0168e+00, 9.7906e+00, 3.4982e-03])


In [17]:
x = torch.randn(3, requires_grad=True)
print(x)

x.requires_grad_(False)
# y = x.detach()
# with torch.no_grad():
#     y = x+2

# print(x)

tensor([1.9336, 0.9268, 0.1436], requires_grad=True)


tensor([1.9336, 0.9268, 0.1436])

In [2]:
weights = torch.ones(4, requires_grad=True)
print(weights)

for epoch in range(3):
    model_output = (weights*3).sum()
    print(model_output)
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [29]:
weights = torch.ones(4, requires_grad=True)

# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step() # an optimization step
# optimizer.zero_grad()

In [15]:
x = torch.ones(3) * 2
x.requires_grad_(True)
print("x = ", x)

y = x*x + x
print("y = ", y)

v = torch.tensor([1, 1, 1], dtype=torch.float32)
y.backward(v)

print(x.grad)

x =  tensor([2., 2., 2.], requires_grad=True)
y =  tensor([6., 6., 6.], grad_fn=<AddBackward0>)
tensor([5., 5., 5.])
