In [1]:
import torch

# Basic Operations

In [3]:
# Returns a tensor filled with uninitialized data.
x = torch.empty(2, 3)

print(x)

tensor([[0.0000e+00, 7.7071e-44, 1.8754e+28],
        [1.2870e+22, 2.5812e-09, 1.0131e-11]])


In [5]:
# Returns a tensor filled with random numbers from a uniform distribution
x = torch.rand(2, 2)

print(x)

tensor([[0.0822, 0.6017],
        [0.5335, 0.2787]])


In [6]:
# Returns a tensor filled with the scalar value `0`
x = torch.zeros(2, 2, 2)

print(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [9]:
# Returns a tensor filled with the scalar value `1`
x = torch.ones(4, 2, dtype=torch.float32)

print(x)

# datatype
print(x.dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
torch.float32


In [13]:
x = torch.tensor([2.5, 0.1])

print(x)

tensor([2.5000, 0.1000])


In [19]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x+y
z = torch.add(x, y)
print(z)

tensor([[0.5300, 0.5096],
        [0.9670, 0.8136]])
tensor([[0.6007, 0.1794],
        [0.3994, 0.3037]])
tensor([[1.1308, 0.6890],
        [1.3664, 1.1173]])


In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

# every function with trailing underscore will do inplace operation
y.add_(x)
print(y)

tensor([[0.1754, 0.4107],
        [0.2779, 0.8296]])
tensor([[0.6106, 0.9699],
        [0.8039, 0.1212]])
tensor([[0.7860, 1.3806],
        [1.0819, 0.9507]])


In [22]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x-y
z = torch.sub(x, y)
print(z)

tensor([[0.3103, 0.9905],
        [0.5397, 0.0527]])
tensor([[0.8154, 0.6875],
        [0.3288, 0.0108]])
tensor([[-0.5051,  0.3031],
        [ 0.2109,  0.0419]])


In [24]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

# matrix multiplication
z = x*y
z = torch.mul(x, y)
print(z)

# Divides each element of the input input by the corresponding element of other
z = x/y
z = torch.div(x, y)
print(z)

tensor([[0.6988, 0.3030],
        [0.5994, 0.9513]])
tensor([[0.0253, 0.4691],
        [0.8146, 0.4600]])
tensor([[0.0177, 0.1421],
        [0.4883, 0.4376]])
tensor([[27.6563,  0.6458],
        [ 0.7359,  2.0680]])


In [30]:
x = torch.rand(5, 3)
print(x)

print(x[:, 0]) # all rows, 0th column

print(x[1, 1])
print(x[1, 1].item()) # to get the value of the tensor

tensor([[0.1029, 0.3008, 0.1006],
        [0.1268, 0.6817, 0.1918],
        [0.2932, 0.4439, 0.5786],
        [0.5797, 0.4376, 0.0298],
        [0.0157, 0.5705, 0.1521]])
tensor([0.1029, 0.1268, 0.2932, 0.5797, 0.0157])
tensor(0.6817)
0.6816670298576355


In [40]:
x = torch.rand(4, 4)
print(x)

# Returns a new tensor with the same data as the self tensor but of a different shape
y = x.view(16)
print(y)

# put -1 and Torch will automatically determine the size
y = x.view(-1, 8)
print(y.shape)

y = x.view(-1, 2, 4)
print(y.shape)

tensor([[0.2515, 0.0274, 0.6227, 0.6783],
        [0.9882, 0.6883, 0.8471, 0.9441],
        [0.0949, 0.9621, 0.5532, 0.5818],
        [0.5630, 0.7276, 0.7498, 0.7415]])
tensor([0.2515, 0.0274, 0.6227, 0.6783, 0.9882, 0.6883, 0.8471, 0.9441, 0.0949,
        0.9621, 0.5532, 0.5818, 0.5630, 0.7276, 0.7498, 0.7415])
torch.Size([2, 8])
torch.Size([2, 2, 4])


# numpy to torch

In [41]:
import numpy as np

In [43]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [44]:
a.add_(1)
print(a)
print(b) # they both point to same memory location

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [50]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b) # happens when tensor is on GPU

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [54]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    x = torch.ones(5, device=device)
    
    y = torch.ones(5)
    y = y.to(device) # move it to device (GPU)
    
    z = x+y
    z = z.to("cpu")
    z.numpy() # error, can handle only cpu tensors (TypeError)

In [55]:
x = torch.ones(5, requires_grad=True) # variable which needs to be optimized later
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
