In [21]:
import torch
import torchvision
from torch.utils.data import Dataset
import numpy as np

In [22]:
class WineDataset(Dataset):
    def __init__(self, transform=None):
        xy = np.loadtxt('Data/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]
        
        # don't convert to tensor
        self.x_data = xy[:, 1:]
        self.y_data = xy[:, [0]]
        
        self.transform = transform
        
    def __getitem__(self, index):
        sample = self.x_data[index], self.y_data[index]
        
        if self.transform:
            sample = self.transform(sample)
            
        return sample
            
    def __len__(self):
        return self.n_samples

In [23]:
# custom Transforms
class ToTensor:
    # convert ndarrays to tensors
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [24]:
class MulTransform:
    # multiply inputs with a given factor
    def __init__(self, factor):
        self.factor = factor
    
    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

In [25]:
print('Without Transforms')
dataset = WineDataset()
first_data = dataset[0]
print(first_data)
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

Without Transforms
(array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03], dtype=float32), array([1.], dtype=float32))
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03] [1.]


In [26]:
print('With Tensor Transforms')
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
print(first_data)
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

With Tensor Transform
(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [27]:
print('With Tensor & Multiplication Transforms')

composed = torchvision.transforms.Compose([ToTensor(), MulTransform(4)])

dataset = WineDataset(transform=composed)
first_data = dataset[0]
print(first_data)
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

With Tensor & Multiplication Transforms
(tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
        1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
        4.2600e+03]), tensor([1.]))
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
        1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
        4.2600e+03]) tensor([1.])
